### ISSUE TITLE
组合多个Field，并和Binder一起使用的时候Binder不能正常工作

### ISSUE THREAD

**Issue by zzk0803** [vaadin/vaadin-custom-field#22]
I had write a demo refer to https://vaadin.com/components/vaadin-custom-field/java-examples,CustomDateTime Picker,wonder does it work with binder
Unfortunately,I found the property(localdatetime ,which collect by customfield) of bean is Null.
and it's wired it's work when i filled the form in reversed order.
------------------------------ forgive my poor english,i wanna express-------------------
我参照https://vaadin.com/components/vaadin-custom-field/java-examples里的Custom DateTime Picker写了代码后，想试试是不是能和Binder一起工作,结果发现按照自然顺序填写表单，提交时发现binder绑定的BEAN里的LocatDateTime（就是那个用CustomField收集的属性）为NULL

奇怪的是，如果我逆序填写表单，提交发现bean里就有localDateTime的属性了。

My Code:
`package zzk.learn.vaadinsb.ui.componentdemo;

import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.customfield.CustomField;
import com.vaadin.flow.component.datepicker.DatePicker;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.html.Input;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.component.timepicker.TimePicker;
import com.vaadin.flow.data.binder.Binder;
import com.vaadin.flow.router.Route;
import zzk.learn.vaadinsb.ui.MainView;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Objects;
import java.util.function.Function;

@Route(value = "customfield", layout = MainView.class)
public class CustomFieldExplorerView extends VerticalLayout {
    public static class SingleElementsWrapping extends CustomField<String> {
        private final TextField textField = new TextField();

        public SingleElementsWrapping() {
            setLabel("Name");
            add(textField);
        }

        @Override
        protected String generateModelValue() {
            return textField.getValue();
        }

        @Override
        protected void setPresentationValue(String newValue) {
            textField.setValue(newValue);
        }
    }

    public static class NativeInput extends CustomField<String> {
        private final Input input = new Input();

        public NativeInput() {
            setLabel("native");
            input.setType("number");
            add(input);
        }

        @Override
        protected String generateModelValue() {
            return input.getValue();
        }

        @Override
        protected void setPresentationValue(String newPresentationValue) {
            this.input.setValue(newPresentationValue);
        }
    }

    public static class DecimalNumberField extends CustomField<BigDecimal> {
        private final TextField integerField = new TextField("Integer");
        private final Label point = new Label("·");
        private final TextField fractionalField = new TextField("fraction");

        private final Div displayDiv = new Div();

        public DecimalNumberField() {
            super(BigDecimal.ZERO);

            setLabel("Decimal Field");

            addValueChangeListener(event -> {
                displayDiv.setText(event.getValue().toPlainString());
            });

            HorizontalLayout panel = new HorizontalLayout(integerField, point, fractionalField);
            panel.setDefaultVerticalComponentAlignment(Alignment.CENTER);
            panel.setVerticalComponentAlignment(Alignment.END, point);
            add(panel);
            add(displayDiv);
        }

        @Override
        protected BigDecimal generateModelValue() {
            try {
                Function<TextField, Integer> toNumber =
                        field -> !field.isEmpty() ? Integer.valueOf(field.getValue()) : 0;
                int i = toNumber.apply(integerField);
                int f = toNumber.apply(fractionalField);
                return new BigDecimal(i + "." + f);
            } catch (NumberFormatException e) {
                return BigDecimal.ZERO;
            }
        }

        @Override
        protected void setPresentationValue(BigDecimal newPresentationValue) {
            if (newPresentationValue == null) {
                integerField.setValue(null);
                fractionalField.setValue(null);
            } else {
                String[] parts = newPresentationValue.toPlainString().split("\\.");
                integerField.setValue(parts[0]);
                integerField.setValue(parts.length > 1 ? parts[1] : null);
            }
        }

    }

    public static class LocalDateTimeField extends CustomField<LocalDateTime> {
        private DatePicker datePicker;
        private TimePicker timePicker;

        public LocalDateTimeField() {
            datePicker = new DatePicker();
            timePicker = new TimePicker();
            add(datePicker,timePicker);
            setLabel("");
        }

        public LocalDateTimeField(String labelName) {
            this();
            setLabel(labelName);
        }

        @Override
        protected LocalDateTime generateModelValue() {
            LocalDate localDate = this.datePicker.getValue();
            LocalTime localTime = this.timePicker.getValue();
            return (Objects.nonNull(localDate) && Objects.nonNull(localTime))
                    ? LocalDateTime.of(localDate, localTime)
                    : null;
        }

        @Override
        protected void setPresentationValue(LocalDateTime newPresentationValue) {
            datePicker.setValue(newPresentationValue != null ?
                    newPresentationValue.toLocalDate() :
                    null);
            timePicker.setValue(newPresentationValue != null ?
                    newPresentationValue.toLocalTime() :
                    null);
        }
    }

    public static class withBinderTestTheCustomField extends Composite<FormLayout> {
        public static class Man {
            private String name;
            private LocalDateTime birthtime;

            public Man() {
            }

            public String getName() {
                return name;
            }

            public void setName(String name) {
                this.name = name;
            }

            public LocalDateTime getBirthtime() {
                return birthtime;
            }

            public void setBirthtime(LocalDateTime birthtime) {
                this.birthtime = birthtime;
            }

            @Override
            public boolean equals(Object o) {
                if (this == o) return true;
                if (!(o instanceof Man)) return false;

                Man man = (Man) o;

                if (getName() != null ? !getName().equals(man.getName()) : man.getName() != null) return false;
                return getBirthtime() != null ? getBirthtime().equals(man.getBirthtime()) : man.getBirthtime() == null;
            }

            @Override
            public int hashCode() {
                int result = getName() != null ? getName().hashCode() : 0;
                result = 31 * result + (getBirthtime() != null ? getBirthtime().hashCode() : 0);
                return result;
            }

            @Override
            public String toString() {
                return "Man{" +
                        "name='" + name + '\'' +
                        ", birthField=" + birthtime +
                        '}';
            }
        }

        private FormLayout root = new FormLayout();
        private VerticalLayout layout = new VerticalLayout();

        private TextField nameField;
        private LocalDateTimeField birthField;

        private Binder<Man> manBinder;
        private Man editing = new Man();

        public withBinderTestTheCustomField() {
            nameField = new TextField("姓名");
            birthField = new LocalDateTimeField("出生具体时间");

            manBinder = new Binder<>();
            manBinder.forField(nameField)
                    .bind(Man::getName, Man::setName);
            manBinder.forField(birthField)
                    .bind(Man::getBirthtime, Man::setBirthtime);
            manBinder.setBean(new Man());

            layout.add(nameField, birthField);

            Button submit = new Button("提交");
            submit.addClickListener(event -> {
                manBinder.writeBeanIfValid(this.editing);
                Notification.show(this.editing.toString());
            });
            layout.add(submit);
            root.add(layout);
        }

        @Override
        protected FormLayout initContent() {
            return this.root;
        }
    }

    public CustomFieldExplorerView() {
        add(new SingleElementsWrapping());
        add(new NativeInput());
        add(new DecimalNumberField());
        add(new LocalDateTimeField());
        add(new withBinderTestTheCustomField());
    }
}
`

**Comment by tulioag** [comment]
Thanks for reporting this issue. It seems the error is not related to binder and can be reproduced in the demo at https://vaadin.com/components/vaadin-custom-field/html-examples/custom-field-basic-demos.

In the last example, changing the date field produces a change-event as expected, but the event is not being generated if you change the time field.

**Comment by web-padawan** [comment]
The missing "change" event for time-picker has been added in vaadin/vaadin-time-picker#110
It is available in `vaadin-time-picker` release and will be available in V14 stable release.

So I'm closing this issue as fixed.
