### ISSUE TITLE
Alignment in form layout is still broken

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-custom-field#35]
Alignment in form-layout is still broken after #23 (also width, see #28).

```html
<vaadin-form-layout>
  <vaadin-combo-box placeholder="vaadin-combo-box"></vaadin-combo-box>
  <vaadin-custom-field>
    <vaadin-combo-box placeholder="vaadin-custom-field"></vaadin-combo-box>
  </vaadin-custom-field>
</vaadin-form-layout>
```

produces:

<img width="554" alt="Screenshot 2019-06-05 at 12 40 15" src="https://user-images.githubusercontent.com/851745/58950440-17bf5900-878f-11e9-9ae6-02462ec0356b.png">

Glitch: https://moor-insect.glitch.me/

Not sure if related also to #26 (seems different to me).

**Comment by web-padawan** [comment]
Let's cover this in scope of #26. Closing as duplicate.

**Comment by samiheikki** [comment]
<img width="478" alt="Screenshot 2019-06-09 at 9 18 35" src="https://user-images.githubusercontent.com/8615573/59155657-9706a280-8a97-11e9-8a9b-13d705c3e2dd.png">

In both FF and Chrome example seems to be working.

**Comment by heruan** [comment]
Sorry @samiheikki my bad: I edited the glitch after posting the screenshot, trying to use `vaadin-horizontal-layout` instead of `vaadin-form-layout`. As you have seen, with the horizontal layout the alignment is fine; I've just reverted back to the form layout and if you open the glitch now you'll see the alignment issue!
