### ISSUE TITLE
CustomField container don't show 

### ISSUE THREAD

**Issue by goransol** [vaadin/vaadin-custom-field#45]
CustomField got problem with content width.

Need to change styles to see components:
```

<dom-module id="custom-field" theme-for="vaadin-custom-field">
    <template>
        <style>

            .container{
                width:100%;
            }

        </style>
    </template>
</dom-module>
  
```

**Comment by juhopiirainen** [comment]
Moved to vaadin-custom-field for further investigation

**Comment by tomivirkki** [comment]
@yuriy-fix is the `.container` element intentionally left without "100%" width?

**Comment by TatuLund** [comment]
I think this is a major flaw. I tried to use CustomField for specific selection field by using TreeGrid inside it and only way to get it to work is to use fixed size for the TreeGrid. It seems that currently CustomField cannot be used in sensible way for anything which contain slightly more complex structures.
