### ISSUE TITLE
Required state for vaadin-rich-text-editor doesn't work

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-custom-field#52]
With #31 the required indicator was fixed for text fields, but it still doesn't work correctly with `vaadin-rich-text-editor`:

```html
<vaadin-custom-field label="Rich text" required>
  <vaadin-rich-text-editor required placeholder="Type something"></vaadin-rich-text-editor>
</vaadin-custom-field>
```

<img width="225" alt="Screenshot 2019-10-07 at 11 51 10" src="https://user-images.githubusercontent.com/851745/66302203-c66bd580-e8f8-11e9-9321-c07f0eb68685.png">

Glitch: https://glitch.com/~glacier-plier

**Comment by heruan** [comment]
Also: a RTE with pre-existing content should not display the blue dot, but it does:

<img width="225" alt="Screenshot 2019-10-07 at 11 55 20" src="https://user-images.githubusercontent.com/851745/66302540-69bcea80-e8f9-11e9-8d10-5a7e650a6548.png">

**Comment by web-padawan** [comment]
Closing in favor of https://github.com/vaadin/vaadin-rich-text-editor/issues/109 as the APIs need to be added in the component.
