### ISSUE TITLE
Strict checks required when accessing inputs

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-custom-field#57]
In certain cases the field may have non-input/non-focusable content; so, this line is problematic:

https://github.com/vaadin/vaadin-custom-field/blob/49ce5cfe39401570710e289292518c7d01f12c8e/src/vaadin-custom-field-mixin.html#L129

To fix this, the `inputs` length *and* existence of a `focus` method should be checked first.

**Comment by web-padawan** [comment]
1. `inputs` are [collected](https://github.com/vaadin/vaadin-custom-field/blob/49ce5cfe39401570710e289292518c7d01f12c8e/src/vaadin-custom-field-mixin.html#L168) based on the presence of `validate` / `checkValidity`. These methods only make sense on HTML elements, and the latter is available on the native `<input>`:
```js
'checkValidity' in HTMLInputElement.prototype; // result: true
```

2. Any HTML element has `focus()` method as you can verify by checking:
```js
'focus' in HTMLElement.prototype; // result: true
```

So this situation is unlikely to happen (unless someone monkey patches any non-element node, e.g. HTML `<!-- comment -->` node to have `validate` or `checkvalidity` methods).

However we can change the line to ensure `inputs[0]` exists when calling `focus()`:

```js
this.inputs && this.inputs[0] && this.inputs[0].focus(); 
```

**Comment by heruan** [comment]
@web-padawan Thanks, I've updated my PR if that may help!
