### ISSUE TITLE
Line-height fix for baseline alignment is problematic

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/vaadin-custom-field#65]
This line was added to the lumo theme in order to make custom-fields align properly with other single-line fields in layouts:
```
        /* align with text-field height + vertical paddings */
        line-height: calc(var(--lumo-text-field-size) + 2 * var(--lumo-space-xs));
```
While I definitely see the point, it does mess up wrapped components that are not "textfield-height", e.g. `vaadin-radio-group` or `vaadin-button` with Lumo theme "small".

Does the line-height have to be applied to slotted children as well, or could it be "reset" to `--lumo-line-height-m` for those?

Alternately, perhaps an attribute, theme variant or some such to toggle this on/off could be added?

**Comment by rolfsmeds** [comment]
Alternately, `vaadin-button` etc could define `line-height` values internally, overriding the one set by `custom-field`.

**Comment by Frettman** [comment]
Just stumbled across this issue: Within a CustomField, the content of Buttons is not vertically centered. Now I know why. Is there a workaround?

**Comment by rolfsmeds** [comment]
As a workaround, you can reset the line-height of the button to 1, so either something like
`vaadin-custom-field > vaadin-button { line-height: 1; }`
in your global css, or, in a stylesheet applied to the custom-field's shadow dom:
`::slotted(vaadin-button) { line-height: 1; }`

**Comment by web-padawan** [comment]
Note, the `button` issue is also reported here: vaadin/vaadin-button#137

**Comment by rolfsmeds** [comment]
Closing in favor of https://github.com/vaadin/vaadin-button/issues/137
