### ISSUE TITLE
CustomField should have field helpers

### ISSUE THREAD

**Issue by vaadin-miki** [vaadin/vaadin-custom-field#89]
Client-side code supports helpers, but the interface is not implemented by `CustomField` in the Java code for Vaadin 14.

**Comment by tomivirkki** [comment]
Related https://github.com/vaadin/vaadin-custom-field/issues/91

**Comment by tulioag** [comment]
@vaadin-miki `CustomField` implements the `HasHelper` interface. Did you face issues or is it something else that is missing?

**Comment by vaadin-miki** [comment]
@tulioag for v18 yes, but this ticket is for v14 (the currently supported LTS), which lacks that interface

**Comment by tulioag** [comment]
@vaadin-miki  It is in 14.4 at least 

https://github.com/vaadin/vaadin-flow-components/blob/14.4/vaadin-custom-field-flow-parent/vaadin-custom-field-flow/src/main/java/com/vaadin/flow/component/customfield/CustomField.java

**Comment by vaadin-miki** [comment]
:| no idea then; I would dig up the relevant discussion about this from slack/components, but slack seems to be dead :) anyway, I guess this can be closed
